2024-03-31 22:17:24,924 - INFO - logger configured
2024-03-31 22:17:24,925 - INFO - TestApp instance created
2024-03-31 22:17:24,981 - ERROR - error occurred during command execution
2024-03-31 22:17:24,981 - INFO - Standard Output of app under test:

2024-03-31 22:17:24,981 - INFO - Error Output of app under test:
python3: can't open file 'appConsoleDeclaration': [Errno 2] No such file or directory

2024-03-31 22:17:24,981 - INFO - TestApp appConsoleDeclaration.py OK
2024-03-31 22:17:24,981 - INFO - test duration: {test.duration}
2024-03-31 22:19:37,868 - INFO - logger configured
2024-03-31 22:19:37,869 - INFO - TestApp instance created
2024-03-31 22:19:47,904 - WARNING - Timeout for ['python3', 'appConsoleDeclaration.py'] (10s) expired
2024-03-31 22:19:47,905 - INFO - Terminating the whole process group...
2024-03-31 22:19:47,908 - INFO - TestApp appConsoleDeclaration.py OK
2024-03-31 22:19:47,909 - INFO - test duration: {test.duration}
